application: jsconf-wifi
runtime: python
version: 1
api_version: 1

handlers:
- url: /
  static_files: static/wifi.html
  upload: static/wifi.html
- url: /(.+)
  static_files: static/\1
  upload: static/(.+)